[package]
name = "parquet_ext"

[package.version]
workspace = true

[package.authors]
workspace = true

[package.edition]
workspace = true

[dependencies]
arrow = { workspace = true }
arrow_ext = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
common_util = { workspace = true }
datafusion = { workspace = true }
log = { workspace = true }
parquet = { workspace = true }
tokio = { workspace = true }
