# Copyright 2023 The CeresDB Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

runtime_thread_num = 4

[rebuild_sst]
store_path = "/tmp/ceresdb/benchmarks"
input_file_name = "898.sst"
read_batch_row_num = 8192
output_file_name = "tt_t.sst"
num_rows_per_row_group = 8192
compression = "SNAPPY"

[rebuild_sst.predicate]
start_time_ms = 0
end_time_ms = 0

[merge_sst]
store_path = "/tmp/ceresdb/benchmarks/2199023255564"
space_id = 1
table_id = 1
sst_file_ids = [1, 17, 19, 24, 31, 37, 43, 45, 9, 14, 18, 21, 27, 34, 40, 44, 5]
dedup = true
read_batch_row_num = 16384
output_store_path = "/tmp/ceresdb/data/1/1"
output_file_name = "16384-all.sst"
num_rows_per_row_group = 16384

[merge_sst.predicate]
start_time_ms = 0
end_time_ms = 0
